【卒業試験】README作成
usg2325/graduation_examination pull request #1
Opened 2024-03-18 10:20 UTC by usg2325

■ サービス概要
Spotifyのプレイリストを自動で作成するサービスです。
ユーザーにお気に入りの曲やアーティストを登録してもらい、それをもとにユーザーの好みに合わせたプレイリストを作成します。
作成するプレイリストには、お気に入りとして登録された曲や、アーティストの曲が含まれないようにし、新しい音楽の発見を促します。

■ このサービスへの思い・作りたい理由
ストリーミングサービスによって数多くの曲を手軽に聴くことができるようになっていますが、つい同じアーティストの曲やお気に入りの曲ばかりを聴いてしまい、マンネリ化してしまうことがあります。
そこで、新しい音楽の発見の手助けになるようなサービスを作成したいと考えました。

■ ユーザー層について
- 自分の好みを基に新しい音楽を発見したい人

■サービスの利用イメージ
ユーザーが普段聴かないアーティストの曲を自分で探すことなく手軽に聴くことができ、気軽に自分の知らないアーティストの発掘をすることができます。

■ ユーザーの獲得について

■ サービスの差別化ポイント・推しポイント
Spotifyで自動作成されるおすすめのプレイリストは、主にユーザーの再生履歴を基に作成され、よく聴く曲やアーティストもプレイリストに含まれています。しかし、本アプリでは、ユーザーがよく聴く曲やアーティストをお気に入りとして登録すると、それらが含まれないプレイリストを作成します。

■ 機能候補
- MVPリリースまでに作っていたいもの
  - ユーザー登録
  - ログイン機能
  - お気に入り登録機能（曲、アーティスト）
  - プレイリスト作成機能

- 本リリースまでに作っていたいもの
  - プレイリスト作成の際の詳細設定機能（プレイリストの長さ等）
  - プレイリスト作成履歴の確認機能
  - 作成したプレイリストの削除機能
  - プレイリストのシェア機能

■ 機能の実装方針予定
- Spotify APIを使用して、ユーザーのプレイリストを自動的に作成する

2024-03-18 11:43 UTC, busitora commented on README.md
> +## ユーザーの獲得について
## ユーザーの獲得について

こちらの記載をお願いします！

2024-03-18 11:45 UTC, busitora requested changes

2024-03-18 11:45 UTC, busitora commented on README.md
> +## ユーザー層について
何故このユーザー層を選んだのか、具体的な理由があれば教えてください!!

2024-03-18 11:45 UTC, busitora commented on README.md
> +- Spotify APIを使用して、ユーザーのプレイリストを自動的に作成する
具体的にどのようなAPIエンドポイントを利用する予定なのか、また、プレイリストを作成する際にどのようなアルゴリズムやロジックを考えているのか、より詳細な実装予定について可能なら教えてください!!

2024-03-22 04:44 UTC, Tsuchiya2 commented
私からもゼロベースでレビューいたします。
以下コメントになります。

---

■機能
・使用予定の技術スタックをREADME.mdに記載してください。
・機能拡張性の観点から、README.mdにかかれている以外で考えている追加サービス・追加機能の案を別途項目を設けて良いのでREADME.mdに記載してください。

2024-03-26 03:35 UTC, kenchasonakai commented
Spotifyのスマートシャッフル機能だとやりたいことは満たせないのでしょうか？
評価することでおすすめされる楽曲も変わるしユーザーの手間もかからないので良いのかなとも思うのですが、無料であること以外にスマートシャッフル機能と差別化できるポイントはありますでしょうか？
https://prtimes.jp/main/html/rd/p/000000170.000022249.html

2024-03-31 05:03 UTC, tarakish reviewed
確認しました。LGTMです！
次の課題に進んでください。

2024-12-25 07:57 UTC, merged